# getting base image
FROM mongo

MAINTAINER zak yewchuk <zk977238@dal.ca>

CMD ["mongodb"]

ENV MONGO_INITDB_ROOT_USERNAME=mongoadmin
ENV MONGO_INITDB_ROOT_PASSWORD=secret#

 
WORKDIR C: \\mongoDB\\datafiles


EXPOSE 27015
EXPOSE 27115
